#!/bin/bash

yum update -y
yum -y install git docker
service docker restart
curl -L "https://github.com/docker/compose/releases/download/1.24.1/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
chmod +x /usr/local/bin/docker-compose
git clone https://github.com/autopilotpattern/hello-world.git
cd hello-world
docker-compose up -d
